### ISSUE TITLE
error in blast2bed

### ISSUE THREAD

**Issue by sgordon007** [jlevy44/Joshua-Levy-Synteny-Analysis#4]
c6/98d480] Submitted process > BlastOff (1)
WARN: No more task to compute -- Execution may be stalled (see the log file for details)
WARN: No more task to compute -- Execution may be stalled (see the log file for details)
[25/5ac550] Submitted process > blast2bed (1)
ERROR ~ Error executing process > 'blast2bed (1)'

Caused by:
  Process `blast2bed (1)` terminated with an error exit status (1)

Command executed:

  #!/bin/bash
  cd /global/projectb/scratch/sgordon/polysCRACKER/run_dirs/wheat.1_5Mbp.k23
  python subgenomeClusteringInterface.py blast2bed ./blast_files/Chinese_Spring_v10_pseudomolecules_161010_shreded_split.kcount.BLASTtsv.txt 1

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "subgenomeClusteringInterface.py", line 1737, in <module>
      main()
    File "subgenomeClusteringInterface.py", line 1735, in main
      options[funct](tuple(arguments))
    File "subgenomeClusteringInterface.py", line 145, in blast2bed
      b = pybedtools.BedTool('blasted.bed').sort().merge(c=4,o='collapse',)
    File "/global/homes/s/sgordon/.conda/envs/polysCRACKER090617/lib/python2.7/site-packages/pybedtools/bedtool.py", line 806, in decorated
      result = method(self, *args, **kwargs)
    File "/global/homes/s/sgordon/.conda/envs/polysCRACKER090617/lib/python2.7/site-packages/pybedtools/bedtool.py", line 337, in wrapped
      decode_output=decode_output,
    File "/global/homes/s/sgordon/.conda/envs/polysCRACKER090617/lib/python2.7/site-packages/pybedtools/helpers.py", line 356, in call_bedtools
      raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
  pybedtools.helpers.BEDToolsError: 
  Command was:
  
        bedtools sort -i blasted.bed
  
  Error message was:
  terminate called after throwing an instance of 'std::bad_alloc'
    what():  std::bad_alloc

**Comment by jlevy44** [comment]
Thanks! The error is likely a memory issue. I can add an option that will not sort the bed file, and create the clustering matrix using lower memory but more time

**Comment by jlevy44** [comment]
We'll call it lowMemory, and select 1 to run it using lower memory when running blast2bed and generateclusteringMatrix

**Comment by jlevy44** [comment]
Option has been added to pipeline!
